#pragma once
#define purnank int
#define nanuApurnank float
#define motuApurnank double
#define shabd char
#define vakya const char*
#define kasuNai void
#define mukhya main
#define jate auto
#define tod break
#define chaluRakh continue
#define baabat case
#define ferfar switch
#define tunku short
#define lambu long
#define mate for
#define jyaSudhi while
#define aiyaJa goto
#define kar do
#define baharThi extern
#define joAgar if
#define nahiTo else
#define pachhuMokal return
#define sthir static
#define mudbhut default
#define nishaniSathe signed
#define nishaniVagar unsigned
#define sangh union
#define maadkhu struct
#define nondh register
//Ganesh no "n"
#define gantar enum
#define aanuMaap sizeof
#define satat const
#define chhaap printf
#define medav scanf
#define shabdMedav getchar
#define shabdMuk putchar
#define vakyaMedav gets
#define vakyaMuk puts
#define kaadh remove
#define screenSaafKar clrscr
#define padhdhati system
#define lakhaanRang textcolor
#define lakhaanPurvbhumika textbackground
#define jagyaKar malloc
#define jagyaKarineSaafKar calloc
#define azaad free